name: CI

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}

    env:
      CI: 'true'

    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Lint JS
        run: yarn lint:js
      - name: Lint HBS
        run: yarn lint:hbs
      - name: Test
        run: yarn test

  try-scenarios:
    name: ${{ matrix.ember-try-scenario }}
    runs-on: ubuntu-latest
    needs: test

    env:
      CI: 'true'

    strategy:
      fail-fast: true
      matrix:
        ember-try-scenario:
          - ember-3.13
          - ember-release
          - ember-beta
          - ember-canary
          - ember-default

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Test
        env:
          EMBER_TRY_SCENARIO: ${{ matrix.ember-try-scenario }}
        run: yarn try:one $EMBER_TRY_SCENARIO

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Git
        run: |
          git config --global user.name "Tomster"
          git config --global user.email "tomster@emberjs.com"
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.1.1
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install yarn
        run: npm install -g yarn
      - name: Install dependencies
        run: yarn install
      - name: Deploy
        run: yarn workspace docs ember deploy production
